# Generated by Django 4.2 on 2025-02-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pvz",
            name="warehouse_address",
            field=models.TextField(blank=True, null=True, verbose_name="Адрес склада"),
        ),
        migrations.AddField(
            model_name="pvz",
            name="warehouse_address_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Адрес склада (EN)"
            ),
        ),
    ]
