# Generated by Django 4.2 on 2025-02-03 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0002_pvz_warehouse_address_pvz_warehouse_address_en"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pvz",
            name="warehouse_address",
        ),
        migrations.RemoveField(
            model_name="pvz",
            name="warehouse_address_en",
        ),
    ]
