# Generated by Django 4.2 on 2025-02-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_courieruser_alter_courier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='mbank',
            field=models.ImageField(blank=True, null=True, upload_to='mbank', verbose_name='Фото QR-кода от MBANK'),
        ),
    ]
