# Generated by Django 4.2 on 2025-02-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_pvz_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(editable=False, help_text='Автоматически рассчитывается', verbose_name='Цена сом'),
        ),
    ]
