# Generated by Django 4.2 on 2025-02-09 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0002_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Введите адрес доставки",
                        max_length=155,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите номер телефона",
                        max_length=20,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "type_payment",
                    models.CharField(
                        choices=[("MBANK", "MBANK"), ("Наличный", "Наличный")],
                        max_length=20,
                        verbose_name="Тип платежа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="Статус доставки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web_app.product",
                        verbose_name="Трек номер",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курьер",
                "verbose_name_plural": "Курьеры",
                "ordering": ["-created_at"],
            },
        ),
    ]
