# Generated by Django 4.2 on 2025-02-10 17:25

import app.web_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_settings_mbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='mbank',
            field=models.ImageField(blank=True, null=True, upload_to=app.web_app.models.mbank_upload_path, verbose_name='Фото QR-кода от MBANK'),
        ),
    ]
