# Generated by Django 4.2 on 2025-01-29 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=70, verbose_name='Трек номер')),
                ('weight', models.FloatField(help_text='Килограм товара', verbose_name='КГ')),
                ('price', models.FloatField(editable=False, help_text='Автоматически рассчитывается', verbose_name='Цена ($)')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает поступления'), ('in_transit', 'В пути'), ('in_office', 'В офисе (Бишкек)'), ('courier_in_transit', 'Курьер в пути'), ('delivered', 'Доставлен'), ('unknown', 'Неизвестный товар')], default='waiting', max_length=20, verbose_name='Статус')),
                ('created_by_manager', models.BooleanField(default=False, verbose_name='Добавлено менеджером')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
