# Generated by Django 4.2 on 2025-02-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0003_remove_pvz_warehouse_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.FloatField(
                blank=True, help_text="Килограм товара", null=True, verbose_name="КГ"
            ),
        ),
    ]
