# Generated by Django 4.2 on 2025-02-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='phone_pvz',
            field=models.CharField(default=1, help_text='Тут нужен рабочий номер склада в Кыргызстане', max_length=50, verbose_name='Номер телефона склада в Кыргызстане'),
            preserve_default=False,
        ),
    ]
