# Generated by Django 4.2 on 2025-02-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0004_alter_settings_mbank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Ожидает поступления"),
                    ("in_transit", "В пути"),
                    ("in_office", "В офисе"),
                    ("courier_in_transit", "Курьер в пути"),
                    ("delivered", "Доставлен"),
                    ("completed", "Завершён"),
                    ("unknown", "Неизвестный товар"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
