# Generated by Django 4.2 on 2025-02-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0004_alter_product_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="pvz",
            name="slug",
            field=models.TextField(null=True, unique=True, verbose_name="SLUG"),
        ),
    ]
