# Generated by Django 4.2 on 2025-02-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_settings_phone_pvz'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address_pvz',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылку на карту'),
        ),
    ]
