# Generated by Django 4.2 on 2025-01-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_product_created_at_alter_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
