# Generated by Django 4.2 on 2025-02-05 09:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0005_pvz_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="about",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="О нас"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="instructions",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="инструкция"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="prohibited_goods",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="запрещенные товары"
            ),
        ),
    ]
