# Generated by Django 4.2 on 2025-02-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_alter_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courieruser',
            options={'verbose_name': 'Курьер', 'verbose_name_plural': 'Курьеры'},
        ),
        migrations.AlterField(
            model_name='courieruser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='courieruser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес склада в китае'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(help_text='Тут нужен рабочий номер склада в Китае', max_length=50, verbose_name='Номер телефона склада в Китае'),
        ),
    ]
