# Generated by Django 4.2 on 2025-02-05 09:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0006_settings_about_settings_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="address_tg_bot",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Адрес склада"
            ),
        ),
    ]
