# Generated by Django 4.2 on 2025-02-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0006_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="price",
            field=models.FloatField(default=1, verbose_name="Цена за кг"),
            preserve_default=False,
        ),
    ]
