# Generated by Django 4.2 on 2025-02-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_alter_courieruser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courieruser',
            name='chat_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='CHAT-ID'),
        ),
    ]
