# Generated by Django 4.2 on 2025-02-05 13:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0007_settings_address_tg_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="support",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Поддержка"
            ),
        ),
    ]
