# Generated by Django 4.2 on 2025-02-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0007_settings_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="ista",
            field=models.URLField(blank=True, null=True, verbose_name="Инстаграмм"),
        ),
        migrations.AddField(
            model_name="settings",
            name="watapp",
            field=models.URLField(blank=True, null=True, verbose_name="Ватсап"),
        ),
    ]
