# Generated by Django 4.2 on 2025-02-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_alter_courieruser_chat_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
