# Generated by Django 4.2 on 2025-02-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0008_alter_courieruser_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="date",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Часы работы"
            ),
            preserve_default=False,
        ),
    ]
